### ISSUE TITLE
When you click on a top tier section is starts off blank.

### ISSUE THREAD

**Issue by sdeering** [Vertafore/grunt-docular#11]
When you click on a top tier section is starts off blank.

![image](https://f.cloud.github.com/assets/1787454/1703584/430efb50-60b8-11e3-86c0-e4ebec2ddc73.png)

Leads to this:

![image](https://f.cloud.github.com/assets/1787454/1703575/197dcd98-60b8-11e3-94ca-f0c40c8fbbaa.png)

Then

![image](https://f.cloud.github.com/assets/1787454/1703593/6b085782-60b8-11e3-843d-7f2b76da561b.png)

Is there anyway to get it to display the whole list from first click?

**Comment by gitsome** [comment]
Whoa, never seen this one before.  I'll take a look. I may not be able to get to these issues until this weekend. Thanks a ton for the details and screenshot, very helpful!

**Comment by willmendesneto** [comment]
This occurring with me too. This issue  already solved?

**Comment by altsanz** [comment]
This happens to me also on version:
    "grunt-docular": "^0.2.4"

and Ubuntu 12.04 LTS
