### ISSUE TITLE
where is the docs outputted?

### ISSUE THREAD

**Issue by jonbcampos** [Vertafore/grunt-docular#12]
Below is my terminal output. It appears to spit out code but I can't find where:

-------- verifying plugins --------
-------- generating Docs --------
Extracting docular Docs For Section "docularinstall"...
Extracting docular Docs For Section "docularinstall"...
Extracting docular Docs For Section "docularconfigure"...
Extracting docular Docs For Section "docularcreate"...
Extracting docular Docs For Section "embed"...
Extracting docular Docs For Section "basics"...
Extracting docular Docs For Section "doctypes"...
Extracting docular Docs For Section "docularext"...
Extracting docular Docs For Section "docular"...
Extracting docular Docs For Section "sublime"...
Extracting docular Docs For Section "docularfaq"...
Extracting example Docs For Section "globals"...
Extracting example Docs For Section "doctypes"...
Extracting angular Docs For Section "api"...
Extracting angular Docs For Section "guide"...
Extracting angular Docs For Section "tutorial"...
Extracting angular Docs For Section "misc"...
-------- generating partials directories for groups --------
-------- generating partials directories for sections --------
-------- merging child docs with parent docs --------
BAD LINK: documentation/angular/cookbook/index
BAD LINK: documentation/docular/basics/booyah
-------- generating partials --------
-------- generating supporting files --------
-------- generating index.html page --------
-------- gathering all doc_api, plugin, and configured css and js --------
-------- generating report --------
DONE! Generated 283 pages in 4786 ms. Partials per second : 59

**Comment by apinstein** [comment]
by default they end up deep in node_modules... but use this to put them wherever you like: http://grunt-docular.com/documentation/docular/docularconfigure/docular-webapp-target
