### ISSUE TITLE
TypeError: Cannot read property 'source' of null

### ISSUE THREAD

**Issue by Kadajett** [Vertafore/grunt-docular#15]
Just a basic service file in an angular application. 

When creating a service file, the documentation group shows up, but only shows the functions on the page if you change the search filter. Seems like it could be a default filter value, or an ng-pristine issue. I will look into it to see if I get fix it or get soem more information.

**Comment by connorbode** [comment]
I have this same issue.  I thought the entire package was broken but at least now I can create & view docs.  This bug almost prevented me from using grunt docular.

Have you found a solution yet?

**Comment by connorbode** [comment]
**this only happens when you specify @id in the @name field** (as demonstrated by an example)

If you specify @id **and** @name properly, this does not occur.

**Comment by stephenliberty** [comment]
Rewrite on core done, this shouldn't exist anymore.
