### ISSUE TITLE
removing server from docular

### ISSUE THREAD

**Issue by idanbauer** [Vertafore/grunt-docular#18]
Hi stephen. 
I think it would be a good idea to move docular server from docular to grunt-docular to allow docular to concentrate on documentation generation. 
I'll be happy to create the appropriate task and create a pull request.

let me know if you're interested

**Comment by stephenliberty** [comment]
Well, the docular server part was completely removed from docular. I'm not sure that I actually want the project to be at all responsible for serving up generated files - especially when there are a half dozen different grunt tasks that can do that with minimal setup. For example, I use https://github.com/devpaul/grunt-devserver - it's simple, and it serves up the files with no issue.. though it doesn't handle html5mode.

**Comment by idanbauer** [comment]
I totally agree with the fact that docular should not container a built in server but I think it makes the product much nicer to use if it comes with an easy way to operate. 
What I did is I enhanced grunt-docular and not docular itself to depend on express and provide an html5mode compliant server with a nice live reload flow to writing docs. 
I realize it may not be aligned with your project goals so I'm currently created a mirror npm package off my fork. If you're interested let me know and I'll submit a pull request.

**Comment by stephenliberty** [comment]
You've piqued my interest. Can you shoot over a link to the code?

**Comment by idanbauer** [comment]
Sure,
https://github.com/idanush/grunt-docular/blob/expressServer/tasks/docular.js
For the reload flow you need to configure grunt-contrib-watch but we can easily put it in the readme.md (I'll do it of course).  
I still need to make the connect-livereload optional if relevant.

**Comment by stephenliberty** [comment]
This looks good - short and sweet. Out of curiosity, since I'm not a real html5 mode guru, does this also work if you've navigated into the docs and then hit the 'refresh' button on your browser?

**Comment by idanbauer** [comment]
Yes it would.  What the script does is it checks if it is a known content
location and if it's not it returns index.html so it behaves exactly like
the non html5mode only the logic is server side.
I'll prepare the pull request for your approval.

Cheers
