### ISSUE TITLE
Wierd behavior when including <script> tag in @example

### ISSUE THREAD

**Issue by jasedwards** [Vertafore/grunt-docular#21]
I am trying to document a directive that has a couple complex properties on it.  Because of this I am using a controller just like angular.js does it in their documentation.  Adding this tag causes all kinds or problems when the documentation is generated.   Here is result:

![docularresult](https://cloud.githubusercontent.com/assets/5818023/3827156/e014a3a4-1d6a-11e4-8e97-82b2bf488d9d.png)

My code looks like this.  Am I doing something wrong?  I have tried everything short of banging my head against the wall:

![code](https://cloud.githubusercontent.com/assets/5818023/3827186/2b431130-1d6b-11e4-980a-56ed705d39f1.png)

Two exceptions are thrown from this:
1.  Unterminated string constant 
2.  Argument '\"Controller\"' is not a function...

**Comment by stephenliberty** [comment]
Hey there,

Can you please paste over the actual code rather than screenshots? I can barely read what you've attached. 

Thanks,
Stephen
