### ISSUE TITLE
External Js link for @example

### ISSUE THREAD

**Issue by jasedwards** [Vertafore/grunt-docular#22]
I have a couple directives that require google maps.  I would like to do @example for these but can't figure out how to include external js links.  would I just create my own home partial and put the script tag there?  Can't seem to find any documentation on that.

**Comment by stephenliberty** [comment]
Assuming you are using the most up-to-date version, look in your "node_modules/grunt-docular/node_modules/docular/lib/resources/templates" folder. There's an "example.html" - this is what is loaded within an iframe and the example code is injected in. If you add another script tag in here, it will load for every example. Which may not be preferable, but it will at least work. In the next version, there will be a 'dependencies' tag that will accept an array of other scripts that need to be loaded... but that won't be available for at least another week.

**Comment by jasedwards** [comment]
thanks.  Just read this and it's been a few weeks.  Was that dependencies put in?

**Comment by stephenliberty** [comment]
The dependencies next release which contains the dependency portion is almost done. Probably a few more days to work out a few bugs.

**Comment by stephenliberty** [comment]
Forgot to mention that this is all fixed up. 

```
<example deps="https://maps.googleapis.com/maps/api/js?key=FOO">
......
</example>
```

That'll load the maps JS in as a dependency for that example.
