### ISSUE TITLE
files attribute should be auto expanded

### ISSUE THREAD

**Issue by nimaen** [Vertafore/grunt-docular#23]
Hi,

The documentation is not up to date regarding `scripts` and `docs`sections attributes.
You need to figure out why it's not working by going to the docular git.

And therefore the files should be auto expanded, using `grunt.file.expand()`, if a string is passed as the `files` attributes, which should be always the case :)

**Comment by stephenliberty** [comment]
You are absolutely right - when I first started on the rewrite, it didn't occur to me to check the parameters incoming and expand them - I was expecting everything to already be expanded. I'll get this into the next build - maybe end of the week? Currently moving and I have no internet :)

As an aside, this really belongs in the https://github.com/Vertafore/docular-ng-plugin issue list, as now docular shouldn't be handling any files directly.

**Comment by nimaen** [comment]
Sure, no problem with that :)
Since i'm trying to use Docular for an enterprise project's documentation, I might be able to contribute a lot.

**Comment by stephenliberty** [comment]
Alright, docular goes through anything in the 'files' object (which is created from a combination of docs and src.. and can be added to by plugins via a new event called ProcessGroupConfig) and expands them with grunt. So, it should be all set now.
