### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by mamzellejuu** [Vertafore/grunt-docular#24]
Hi,

I tried this example and it isn't generated:
http://grunt-docular.com/documentation/docular/docularcreate/firstdoc

Is that documentation is up to date?

**Comment by stephenliberty** [comment]
The documentation on the site is **not** up to date. However, that being said, there is a bug that is probably preventing the documentation from being generated. Where you probably have something like.. 

```
scripts: [
    "example/javascript/lib/utilities.js"
],
```

Make that to be the following instead:

```
scripts: [
    grunt.file.expand(["example/javascript/lib/utilities.js"])
],
```

During the refactor I didn't take into account some grunt-style things. I'm hoping to fix this up shortly. Please let me know if you run into any more difficulties.
