### ISSUE TITLE
grunt docularserver doesn't run

### ISSUE THREAD

**Issue by xarling** [Vertafore/grunt-docular#26]
When I run 

```
grunt docularserver
```

I see the following error message:

```
Warning: Arguments to path.join must be strings Use --force to continue.
```

What am I doing wrong?

**Comment by burib** [comment]
you need to specify the Path for docular-server, where your generated documents are.

See example: 
https://github.com/burib/grunt-docular.example/blob/master/gruntfile.js#L33

**Comment by xarling** [comment]
Thank you. Running a server works! I'm getting a different error now, but I'll try to fix that myself
