### ISSUE TITLE
documentation content generation

### ISSUE THREAD

**Issue by burib** [Vertafore/grunt-docular#28]
if I try to generate any dummy documentation, then I cannot get docular to write out the actual documentations content. Even if I turn on 

``` javascript
showDocularDocs: true, 
showAngularDocs: true
```

it's still not working correctly.

https://github.com/burib/grunt-docular.example

please advice.

**Comment by stephenliberty** [comment]
Good catch. Looks like the server task is trying to serve up the website for the site.json file, rather than serving up the actual file. Looking into it.

**Comment by stephenliberty** [comment]
New version should take care of most of the problems, except that `@return` is supposed to be `@returns`

**Comment by burib** [comment]
I've updated the example project and tried it out. Works correctly now. Thanks. Is there any way I can help / contribute ?

**Comment by stephenliberty** [comment]
Mostly just by testing and reporting issues (and fixes, if possible). Especially if you have suggested corrections to the website, which is terribly out of date.
