### ISSUE TITLE
grunt-docular exits build

### ISSUE THREAD

**Issue by sporritt** [Vertafore/grunt-docular#6]
grunt-docular seems to exit the build as soon as it is finished.  if you use it in a list of tasks, anything after it in the list is not executed.  is this by design?

**Comment by sporritt** [comment]
after some more poking around i found it's caused by an issue in docular.  PR here:

https://github.com/gitsome/docular/pull/62

**Comment by gitsome** [comment]
thanks @sporritt, looking into this. I have it fixed in my local from a pull that I thought was already merged... need to dig.

**Comment by sporritt** [comment]
hey..i only just discovered that you replied.  good to hear you've got it sorted!
